x-common-volumes: &common-volumes
  - ./:/MoneyPrinterTurbo

services:
  webui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "moneyprinterturbo-webui"
    ports:
      - "8501:8501"
    command: [ "streamlit", "run", "./webui/Main.py","--browser.serverAddress=127.0.0.1","--server.enableCORS=True","--browser.gatherUsageStats=False" ]
    volumes: *common-volumes
    restart: always
    env_file:
      - .env
    environment:
      - PEXELS_API_KEYS=${PEXELS_API_KEYS}
      - PIXABAY_API_KEYS=${PIXABAY_API_KEYS}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "moneyprinterturbo-api"
    ports:
      - "8080:8080"
    command: [ "python3", "main.py" ]
    volumes: *common-volumes
    restart: always
    env_file:
      - .env
    environment:
      - PEXELS_API_KEYS=${PEXELS_API_KEYS}
      - PIXABAY_API_KEYS=${PIXABAY_API_KEYS}
      - OPENAI_API_KEY=${OPENAI_API_KEY}